/////////////////////////////////////////////////////////////////////////////
// Weed mirrors plugin, version 
// Compiled with Builder version 4.0,0-pre
// autogenerated from script mirrors.script

// released under the GNU GPL version 3 or higher
// see file COPYING or www.gnu.org for details

// (c) salsaman
// and effecTV 2023
/////////////////////////////////////////////////////////////////////////////

static int package_version = 1; // version of this package

/////////////////////////////////////////////////////////////////////////////

#define _UNIQUE_ID_ "0X4847CA06EC91CD4A"

#include <weed/weed-plugin.h>
#include <weed/weed-utils.h>
#include <weed/weed-plugin-utils.h>

#include <weed/weed-plugin-utils/weed-plugin-utils.c>

//////////////////////////////////////////////////////////////////

#include <math.h>

#include <stdio.h>

static int verbosity = WEED_VERBOSITY_ERROR;
typedef unsigned int RGB32
;

static const double scmax = exp(3.);

void foo(void) {

  // code

}


/////////////////////////////////////////////////////////////////////////////

static weed_error_t mirrors_disp_
(weed_plant_t *inst, weed_plant_t *param, int inverse) {
  if (!weed_plant_has_leaf(param, WEED_LEAF_VALUE)) return WEED_ERROR_NOSUCH_LEAF;
  else {
    val = weed_param_get_value_(param);
    if (inverse == WEED_FALSE) {
      log|double|val <= 0.||
      val = log(val) + 1.;
      val = exp(val - 1.);

    }
    return weed_set__value(weed_param_get_gui(param), WEED_LEAF_DISPLAY_VALUE, val);
  }
}


WEED_SETUP_START(203, 202) {
  weed_plant_t *host_info = weed_get_host_info(plugin_info);
  weed_plant_t *filter_class;
  uint64_t unique_id;
  int palette_list[] = ALL_PACKED_PALETTES_PLUS
;
  weed_plant_t *in_chantmpls[] = {
      weed_channel_template_init("in_channel0", WEED_CHANNEL_REINIT_ON_SIZE_CHANGE),
      weed_channel_template_init("in_channel1", 0),
      NULL};
  weed_plant_t *out_chantmpls[] = {
      weed_channel_template_init("out_channel0", WEED_CHANNEL_CAN_DO_INPLACE),
      NULL};
  weed_plant_t *in_paramtmpls[] = {
      weed_integer_init("zoom", "_Zoom value", 128, 0, 255),
      weed_radio_init("autozoom", "_Auto zoom", WEED_TRUE, 
),
      weed_float_init("opac", "_Opacity", 1., 0., 1.),
      weed_colRGBi_init("col", "_Colour", 0, 0, 255),
      NULL};
  weed_plant_t *out_paramtmpls[] = {
      weed_out_param_float_init("relative", 0, 
, ),
      weed_out_param_float_init("absolute", 0, 
, ),
      weed_out_param_float_init("since_reset", 0, 
, ),
      weed_out_param_switch_init("was_reset",  WEED_TRUE),
      NULL};
  weed_plant_t *gui;
  char *rfx_strings[] = {
      "special|ignored|1|
",
      "
",
      NULL};
  weed_plant_t *pgui;
  int filter_flags = 0;

  verbosity = weed_get_host_verbosity(host_info);

  pgui = weed_paramtmpl_get_gui(in_paramtmpls[P_zoom]);
  weed_set_double_value(pgui, WEED_LEAF_STEP_SIZE, 
);
  weed_set_funcptr_value(pgui, WEED_LEAF_DISPLAY_VALUE_FUNC, (weed_funcptr_t)mirrors_disp_log);

  pgui = weed_paramtmpl_get_gui(in_paramtmpls[P_opac]);
  weed_set_int_value(pgui, WEED_LEAF_DECIMALS, 2);
  weed_set_double_value(pgui, WEED_LEAF_STEP_SIZE, 
);

  filter_class = weed_filter_class_init("new_effect|new effect
", "effecTV
", , filter_flags, ,
    , , , in_chantmpls, out_chantmpls, in_paramtmpls, out_paramtmpls);

  weed_set_string_value(filter_class, WEED_LEAF_EXTRA_AUTHORS, "salsaman
");
  gui = weed_filter_get_gui(filter_class);
  weed_set_string_value(gui, WEED_LEAF_LAYOUT_SCHEME, "RFX");
  weed_set_string_value(gui, "layout_rfx_delim", "|");
  weed_set_string_array(gui, "layout_rfx_strings", 2, rfx_strings);

  weed_filter_set_description(filter_class, "A filter which does something cool.
");

  weed_plugin_info_add_filter_class(plugin_info, filter_class);

  if (!sscanf(_UNIQUE_ID_, "0X%lX", &unique_id) || !sscanf(_UNIQUE_ID_, "0x%lx", &unique_id)) {
    weed_set_int64_value(plugin_info, WEED_LEAF_UNIQUE_ID, unique_id);
  }

  do {
    make_tables();

  } while (0);

  weed_plugin_set_package_version(plugin_info, package_version);
}
WEED_SETUP_END;

