#!/usr/bin/perl

my $streamout;
my $streamin;

if (!defined($ARGV[0])) {
   exit 1;
}

my $com=shift;

my $workdir=`smogrify get_workdir`;

if (defined($ARGV[0])) {
   $streamout=shift;
}	
else {
     $streamout="$workdir/glcfifo";
}


if (defined($ARGV[0])) {
   $streamin=shift;
}	
else {
     $streamin="$workdir/stream.yuv";
}


system "./lives-glc-play-norun \"$com\" \"$streamout\" \"$streamin\" @ARGV &";
system "lives -noset -yuvin \"$streamin\"";

