#!/usr/bin/perl


my $streamout;
my $streamin;

if (!defined($ARGV[0])) {
   exit 1;
}

my $com=$ARGV[0];

my $workdir=`smogrify get_workdir`;

if (defined($ARGV[1])) {
   $streamout=$ARGV[1];
}	
else {
     $streamout="$workdir/glcfifo";
}


if (defined($ARGV[2])) {
   $streamin=$ARGV[2];
}	
else {
     $streamin="$workdir/stream.yuv";
}


system "mkfifo \"$streamin\"";
system "mkfifo \"$streamout\"";

#system "glc-capture --disable-audio -b back -i -f 25 -s -z none -c 640x480+192+100 -g -o \"$streamout\" \"$com\" &";

system "glc-capture --disable-audio -b back -i -f 25 -s -z none -g -o \"$streamout\" \"$com\" &";

system "glc-play -f 25 -t \"$streamout\" -y 1 -o \"$streamin\"";

unlink "$streamin";
unlink "$streamout";

