.TH lives 1 "November 12, 2007"
.SH NAME
LiVES \- LiVES is a Video Editing System
.SH SYNOPSIS
.B lives
.SH DESCRIPTION
This manual page documents briefly the
.B lives
command.
.PP
\fBLiVES\fP  lets you start editing and making video right away, without having
to worry about formats, frame sizes, or framerates. LiVES will let you start
creating your own tools, utilities and effects via the built in RFX builder.
.SH SEE ALSO
.BR mplayer (1),
.BR ImageMagick (1),
.BR ffmpeg (1).
.br
.SH AUTHOR
lives was written by Gabriel "Salsaman" Finch.
.PP
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
