.TH ogm_encoder 1 "January 6 2010"
.SH NAME
ogm_encoder \- Video encoder as part of LiVES
.SH DESCRIPTION
ogm_encoder is part of the multi_encoder plugin for lives. To see usage
run ogm_encoder \-h
.SH SEE ALSO
lives(1)
.SH AUTHOR
multi_encoder and all auxiliary encoders are
copyright (C) 2004-2006 Marco De la Cruz (marco@reimeika.ca)
and are released under the GPL license. See
http://www.gnu.org/copyleft/gpl.html for details.
Contributors:
(j@v2v.cc)
Gabriel Finch a.k.a Salsaman (salsaman@xs4all.nl)

This man page was written by Harry Rickards <hrickards@l33tmyst.com>
