#!/bin/bash
# Define spec file version and release
MAINNAME=LiVES
MAINVERS=0.9.5-1

# Get running kernel hint - SMP or non-SMP
if grep -q "smp" /proc/sys/kernel/osrelease ; then
   LOGBOOK=smp
   SMPRELEASE=`uname -r | cut -ds -f1`
   ARCHIVE=`rpm -q --qf %{ARCH} kernel-smp-$SMPRELEASE`
else
   LOGBOOK=
   KRNRELEASE=`uname -r`
   ARCHIVE=`rpm -q --qf %{ARCH} kernel-$KRNRELEASE`
fi

rpmbuild -ba --target=$ARCHIVE $MAINNAME-$MAINVERS.spec 2>&1 | tee ../LOGS/$MAINNAME-$MAINVERS.$ARCHIVE$LOGBOOK.txt
cd ../RPMS/$ARCHIVE
if [ "$LOGBOOK" = "smp" ] ; then
   KERNEL=kernel-smp-`cat /proc/sys/kernel/osrelease | cut -ds -f1`
else
   KERNEL=kernel-`cat /proc/sys/kernel/osrelease | cut -d" " -f1`
fi
md5sum $MAINNAME-$MAINVERS.$ARCHIVE.rpm > $MAINNAME-$MAINVERS.$ARCHIVE.rpm.md5
cd ../../SRPMS
md5sum $MAINNAME-$MAINVERS.src.rpm > $MAINNAME-$MAINVERS.src.rpm.md5
cd ../SPECS
