.TH smogrify 1 "July 28 2009"
.SH NAME
smogrify \- Video editing command for LiVES
.SH SYNOPSIS
smogrify Man Page
.SH DESCRIPTION
smogrify is a backend helper which LiVES (see lives(1) uses to
make any substantial changes to the video you are working with.
.SH SEE ALSO
lives(1)
.SH AUTHOR
lives was written by Gabriel "Salsaman" Finch

This man page was written by Harry Rickards <hrickards@l33tmyst.com>
Some bits sort of taken from the CC-licensed LiVES tutorial, copyrighted to Marco De la Cruz
