#!/usr/bin/perl


if (!defined($ARGV[0])) {
   exit 1;
}

my $vidfile=shift;

my $streamin;

if (defined($ARGV[0])) {
    $streamin=shift;
}	
else {
    my $workdir=`smogrify get_workdir`;
    $streamin="$workdir/stream.yuv";
}


system "lives-play-norun \"$vidfile\" \"$streamin\" @ARGV &";
system "lives -noset -yuvin \"$streamin\"";



