#!/usr/bin/perl

if (!defined($ARGV[0])) {
   exit 1;
}

my $streamin;

my $vidfile=$ARGV[0];

if (defined($ARGV[1])) {
   $streamin=$ARGV[1];
}	
else {
    my $workdir=`smogrify get_workdir`;
    $streamin="$workdir/stream.yuv";
}

system "mkfifo \"$streamin\"";

system "mplayer \"$vidfile\" -vo yuv4mpeg:file=\"$streamin\"";

unlink "$streamin";


