// support.c
// LiVES
// portions of this file were auto-generated by glade, the remainder is (c) G. Finch (salsaman)

// released under the GNU GPL 3 or later
// see file ../COPYING or www.gnu.org for licensing details

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include "support.h"

#ifndef LIVES_INLINE
#ifndef IS_SOLARIS
#define LIVES_INLINE inline
#else
#define LIVES_INLINE
#endif
#endif


#ifdef ENABLE_NLS
LIVES_INLINE gchar *translate(const char *String) {
  if (trString!=NULL) g_free(trString); // be very careful, as trString is free()d automatically here
  if (strlen(String)) trString=g_locale_to_utf8 (dgettext (PACKAGE, String),-1,NULL,NULL,NULL);
  else trString=g_strdup(String);
  return trString;
}

LIVES_INLINE gchar *translate_with_plural(const char *String, const char *StringPlural, unsigned long int n) {
  if (trString!=NULL) g_free(trString); // be very careful, as trString is free()d automatically here
  if (strlen(String)) trString=g_locale_to_utf8 (dngettext (PACKAGE, String, StringPlural, n),-1,NULL,NULL,NULL);
  else trString=g_strdup(String);
  return trString;
}


#endif

static GList *pixmaps_directories = NULL;

/* Use this function to set the directory containing installed pixmaps. */
void
add_pixmap_directory                   (const gchar     *directory)
{
  pixmaps_directories = g_list_prepend (pixmaps_directories,
                                        g_strdup (directory));
}

/* This is an internally used function to find pixmap files. */
static gchar*
find_pixmap_file                       (const gchar     *filename)
{
  GList *elem;

  /* We step through each of the pixmaps directory to find it. */
  elem = pixmaps_directories;
  while (elem)
    {
      gchar *pathname = g_build_filename ((gchar*)elem->data, filename, NULL);
      if (g_file_test (pathname, G_FILE_TEST_EXISTS))
        return pathname;
      g_free (pathname);
      elem = elem->next;
    }
  return NULL;
}

/* This is an internally used function to create pixmaps. */
GtkWidget*
create_pixmap                          (GtkWidget       *widget,
                                        const gchar     *filename)
{
  gchar *pathname = NULL;
  GtkWidget *pixmap;

  if (!filename || !filename[0])
      return gtk_image_new ();

  pathname = find_pixmap_file (filename);

  if (!pathname)
    {
      g_warning (_("Couldn't find pixmap file: %s"), filename);
      return gtk_image_new ();
    }

  pixmap = gtk_image_new_from_file (pathname);
  g_free (pathname);
  return pixmap;
}

/* This is an internally used function to create pixmaps. */
GdkPixbuf*
create_pixbuf                          (const gchar     *filename)
{
  gchar *pathname = NULL;
  GdkPixbuf *pixbuf;
  GError *error = NULL;

  if (!filename || !filename[0])
      return NULL;

  pathname = find_pixmap_file (filename);

  if (!pathname)
    {
      g_warning (_("Couldn't find pixmap file: %s"), filename);
      return NULL;
    }

  pixbuf = lives_pixbuf_new_from_file (pathname, &error);
  if (!pixbuf)
    {
      fprintf (stderr, "Failed to load pixbuf file: %s: %s\n",
               pathname, error->message);
      g_error_free (error);
    }
  g_free (pathname);
  return pixbuf;
}

