// support.h
// LiVES
// portions of this file were auto-generated by glade, the remainder is (c) G. Finch (salsaman) 2002 - 2015

// released under the GNU GPL 3 or later
// see file ../COPYING or www.gnu.org for licensing details

#ifndef HAS_LIVES_SUPPORT_H
#define HAS_LIVES_SUPPORT_H

/*
   Standard gettext macros.
*/
#ifdef ENABLE_NLS

char *translate(const char *String);
char *translate_with_plural(const char *String, const char *StringPlural, unsigned long int n);

/*
   non-Standard gettext macros.
*/
char *translate_with_hash(const char *String);
char *translate_with_plural_hash(const char *String, const char *StringPlural, unsigned long int n);

#  include <libintl.h>
#  include <locale.h>
#  undef _
#  define _(String) (translate(String))
#  define H_(String) (translate_with_hash(String))
#  define P_(String, StringPlural, n) (translate_with_plural(String, StringPlural, n))
#  define h_(String, StringPlural, n) (translate_with_plural_hash(String, StringPlural, n))
#  ifdef gettext_noop
#    define N_(String) gettext_noop(String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain, Message) (Message)
#  define dngettext(Domain, Message, MsgPlur, n) (Message)
#  define dcgettext(Domain, Message, Type) (Message)
#  define bindtextdomain(Domain, Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#  define P_(String, StringPlural, n) (String)
#endif
#endif



